import type { FortuneContentLanguage } from '@/lib/fortune-generator'
import type { MbtiDimension } from './mbti-types'

type MbtiContentLanguage = FortuneContentLanguage | 'hi'

export type LocalizedQuestionRow = Record<
  MbtiContentLanguage,
  { text: string; optionA: string; optionB: string }
>

export const mbtiQuestionRows: {
  id: number
  dimension: MbtiDimension
  locales: LocalizedQuestionRow
}[] = [
  {
    id: 1,
    dimension: 'EI',
    locales: {
      ko: { text: '파티에서 당신은?', optionA: '여러 사람과 대화하며 에너지를 얻는다', optionB: '소수의 친한 사람과 깊은 대화를 선호한다' },
      en: { text: 'At a party, you usually…', optionA: 'Talk with many people and feel energized', optionB: 'Prefer deep conversation with a few close friends' },
      ja: { text: 'パーティーではあなたは？', optionA: '多くの人と話してエネルギーを得る', optionB: '親しい少数と深い会話を好む' },
      zh: { text: '在派对上，你通常会…', optionA: '与很多人交谈并获得能量', optionB: '更喜欢与少数亲密的人深入交流' },
      es: { text: 'En una fiesta, tú sueles…', optionA: 'Hablar con mucha gente y sentirte con energía', optionB: 'Preferir una charla profunda con pocos amigos cercanos' },
      fr: { text: 'Lors d’une fête, vous avez tendance à…', optionA: 'Parler avec beaucoup de monde et vous sentir énergisé', optionB: 'Préférer une conversation profonde avec quelques amis proches' },
      de: { text: 'Auf einer Party neigen Sie dazu…', optionA: 'Mit vielen Menschen zu sprechen und sich energiegeladen zu fühlen', optionB: 'Tiefe Gespräche mit wenigen engen Freunden zu bevorzugen' },
      vi: { text: 'Trong một bữa tiệc, bạn thường…', optionA: 'Trò chuyện với nhiều người và cảm thấy tràn đầy năng lượng', optionB: 'Thích trò chuyện sâu với vài người bạn thân' },
      th: { text: 'ในงานปาร์ตี้ โดยปกติคุณจะ…', optionA: 'คุยกับคนหลายคนและรู้สึกมีพลัง', optionB: 'ชอบคุยลึกๆ กับเพื่อนสนิทไม่กี่คนมากกว่า' },
      id: { text: 'Di pesta, kamu biasanya…', optionA: 'Berbicara dengan banyak orang dan merasa berenergi', optionB: 'Lebih suka percakapan mendalam dengan beberapa teman dekat' },
      pt: { text: 'Em uma festa, você costuma…', optionA: 'Conversar com muitas pessoas e se sentir energizado', optionB: 'Preferir uma conversa profunda com poucos amigos próximos' },
      hi: { text: 'पार्टी में, आप आमतौर पर…', optionA: 'कई लोगों से बात करके ऊर्जावान महसूस करते हैं', optionB: 'कुछ करीबी दोस्तों के साथ गहरी बातचीत पसंद करते हैं' },
    },
  },
  {
    id: 2,
    dimension: 'SN',
    locales: {
      ko: { text: '새로운 프로젝트를 시작할 때?', optionA: '구체적인 계획과 일정을 먼저 세운다', optionB: '큰 그림을 그리고 세부사항은 나중에 정한다' },
      en: { text: 'When starting a new project, you…', optionA: 'Make a concrete plan and schedule first', optionB: 'Sketch the big picture and fill in details later' },
      ja: { text: '新しいプロジェクトを始めるとき？', optionA: 'まず具体的な計画と日程を立てる', optionB: '全体像を描き、細部は後で決める' },
      zh: { text: '开始新项目时，你会…', optionA: '先制定具体计划和时间表', optionB: '先勾勒大局，细节以后再定' },
      es: { text: 'Al empezar un proyecto nuevo…', optionA: 'Primero haces un plan y calendario concretos', optionB: 'Dibujas la visión general y los detalles después' },
      fr: { text: 'Quand vous commencez un nouveau projet…', optionA: 'Vous faites d’abord un plan concret et un calendrier', optionB: 'Vous dessinez d’abord la vision d’ensemble puis ajoutez les détails' },
      de: { text: 'Wenn Sie ein neues Projekt beginnen…', optionA: 'Erstellen Sie zuerst einen konkreten Plan und Zeitplan', optionB: 'Skizzieren Sie zuerst das große Ganze und ergänzen Details später' },
      vi: { text: 'Khi bắt đầu một dự án mới, bạn…', optionA: 'Trước tiên lập kế hoạch và lịch trình cụ thể', optionB: 'Phác thảo bức tranh tổng thể trước rồi bổ sung chi tiết sau' },
      th: { text: 'เมื่อเริ่มโปรเจกต์ใหม่ คุณจะ…', optionA: 'วางแผนและตารางเวลาแบบชัดเจนก่อน', optionB: 'มองภาพรวมก่อนแล้วค่อยเติมรายละเอียดทีหลัง' },
      id: { text: 'Saat memulai proyek baru…', optionA: 'Membuat rencana dan jadwal konkret dulu', optionB: 'Menggambar gambaran besar, detail menyusul' },
      pt: { text: 'Ao começar um projeto novo…', optionA: 'Primeiro você faz um plano e um cronograma concretos', optionB: 'Desenha a visão geral e define os detalhes depois' },
      hi: { text: 'नया प्रोजेक्ट शुरू करते समय, आप…', optionA: 'पहले ठोस योजना और समय-सारिणी बनाते हैं', optionB: 'बड़ी तस्वीर बनाते हैं, विवरण बाद में भरते हैं' },
    },
  },
  {
    id: 3,
    dimension: 'TF',
    locales: {
      ko: { text: '친구가 고민을 말할 때?', optionA: '해결책을 제시하려고 한다', optionB: '공감하고 감정을 이해하려 한다' },
      en: { text: 'When a friend shares a worry, you…', optionA: 'Try to offer solutions', optionB: 'Empathize and try to understand their feelings' },
      ja: { text: '友人が悩みを話すとき？', optionA: '解決策を提案しようとする', optionB: '共感し、気持ちを理解しようとする' },
      zh: { text: '朋友倾诉烦恼时，你会…', optionA: '试着提供解决办法', optionB: '共情并努力理解对方的感受' },
      es: { text: 'Cuando un amigo cuenta una preocupación…', optionA: 'Intentas ofrecer soluciones', optionB: 'Empatizas e intentas entender sus sentimientos' },
      fr: { text: 'Quand un ami vous confie une inquiétude…', optionA: 'Vous essayez de proposer des solutions', optionB: 'Vous faites preuve d’empathie et essayez de comprendre ses sentiments' },
      de: { text: 'Wenn ein Freund Ihnen von einer Sorge erzählt…', optionA: 'Versuchen Sie, Lösungen anzubieten', optionB: 'Zeigen Sie Empathie und versuchen, seine Gefühle zu verstehen' },
      vi: { text: 'Khi một người bạn chia sẻ nỗi lo, bạn…', optionA: 'Cố gắng đưa ra giải pháp', optionB: 'Đồng cảm và cố gắng thấu hiểu cảm xúc của họ' },
      th: { text: 'เมื่อเพื่อนเล่าความกังวลให้ฟัง คุณจะ…', optionA: 'พยายามเสนอทางแก้', optionB: 'เห็นอกเห็นใจและพยายามเข้าใจความรู้สึกของเขา' },
      id: { text: 'Saat teman bercerita masalah…', optionA: 'Mencoba memberi solusi', optionB: 'Berempati dan memahami perasaannya' },
      pt: { text: 'Quando um amigo compartilha uma preocupação…', optionA: 'Você tenta oferecer soluções', optionB: 'Você demonstra empatia e tenta entender os sentimentos dele' },
      hi: { text: 'जब कोई मित्र चिंता साझा करता है, आप…', optionA: 'समाधान देने की कोशिश करते हैं', optionB: 'सहानुभूति रखते हैं और उनकी भावनाओं को समझने का प्रयास करते हैं' },
    },
  },
  {
    id: 4,
    dimension: 'JP',
    locales: {
      ko: { text: '여행 계획은?', optionA: '미리 일정을 세우고 예약한다', optionB: '즉흥적으로 결정하는 것을 좋아한다' },
      en: { text: 'For travel plans, you…', optionA: 'Plan the itinerary and book ahead', optionB: 'Like deciding spontaneously along the way' },
      ja: { text: '旅行の計画は？', optionA: '事前に日程を決めて予約する', optionB: 'その場で決めるのが好きだ' },
      zh: { text: '关于旅行计划，你…', optionA: '提前安排行程并预订', optionB: '喜欢即兴决定' },
      es: { text: 'Con los planes de viaje…', optionA: 'Organizas el itinerario y reservas con antelación', optionB: 'Te gusta decidir sobre la marcha' },
      fr: { text: 'Pour les projets de voyage…', optionA: 'Vous organisez l’itinéraire et réservez à l’avance', optionB: 'Vous aimez décider au fil du moment' },
      de: { text: 'Bei Reiseplänen…', optionA: 'Planen Sie die Reiseroute und buchen im Voraus', optionB: 'Entscheiden Sie lieber spontan unterwegs' },
      vi: { text: 'Về kế hoạch du lịch, bạn…', optionA: 'Lên lịch trình và đặt trước', optionB: 'Thích quyết định ngẫu hứng trong lúc đi' },
      th: { text: 'สำหรับแผนการเดินทาง คุณจะ…', optionA: 'วางแผนเส้นทางและจองล่วงหน้า', optionB: 'ชอบตัดสินใจแบบฉับพลันระหว่างทาง' },
      id: { text: 'Untuk rencana perjalanan…', optionA: 'Menyusun jadwal dan memesan dari awal', optionB: 'Suka memutuskan secara spontan' },
      pt: { text: 'Nos planos de viagem…', optionA: 'Você organiza o roteiro e faz reservas com antecedência', optionB: 'Você gosta de decidir no improviso' },
      hi: { text: 'यात्रा की योजना के लिए, आप…', optionA: 'पहले से यात्रा कार्यक्रम बनाते और बुकिंग करते हैं', optionB: 'रास्ते में सहज निर्णय लेना पसंद करते हैं' },
    },
  },
  {
    id: 5,
    dimension: 'EI',
    locales: {
      ko: { text: '주말에 충전하는 방법?', optionA: '친구들과 만나 활동적으로 보낸다', optionB: '집에서 혼자 취미 활동을 한다' },
      en: { text: 'On weekends you recharge by…', optionA: 'Meeting friends and staying active', optionB: 'Staying home alone with hobbies' },
      ja: { text: '週末の充電方法は？', optionA: '友人と会って活動的に過ごす', optionB: '家で一人で趣味に没頭する' },
      zh: { text: '周末你如何充电？', optionA: '见朋友并活跃地度过', optionB: '在家独处做爱好' },
      es: { text: 'Los fines de semana recargas energías…', optionA: 'Viendo amigos y manteniéndote activo', optionB: 'Quedándote en casa a solas con tus hobbies' },
      fr: { text: 'Le week-end, vous rechargez vos batteries en…', optionA: 'Voyant des amis et en restant actif', optionB: 'Restant chez vous, seul, avec vos hobbies' },
      de: { text: 'Am Wochenende laden Sie Ihre Energie auf, indem Sie…', optionA: 'Freunde treffen und aktiv bleiben', optionB: 'Allein zu Hause mit Ihren Hobbys bleiben' },
      vi: { text: 'Cuối tuần bạn nạp lại năng lượng bằng cách…', optionA: 'Gặp gỡ bạn bè và hoạt động năng nổ', optionB: 'Ở nhà một mình với sở thích cá nhân' },
      th: { text: 'วันหยุดสุดสัปดาห์คุณชาร์จพลังด้วยการ…', optionA: 'ไปเจอเพื่อนและทำกิจกรรมอย่างกระฉับกระเฉง', optionB: 'อยู่บ้านคนเดียวกับงานอดิเรกของตัวเอง' },
      id: { text: 'Di akhir pekan kamu mengisi ulang energi dengan…', optionA: 'Bertemu teman dan tetap aktif', optionB: 'Di rumah sendiri dengan hobi' },
      pt: { text: 'Nos fins de semana, você recarrega as energias…', optionA: 'Encontrando amigos e se mantendo ativo', optionB: 'Ficando em casa sozinho com seus hobbies' },
      hi: { text: 'सप्ताहांत पर आप ऊर्जा भरते हैं…', optionA: 'मित्रों से मिलकर सक्रिय रहकर', optionB: 'घर पर अकेले शौक के साथ' },
    },
  },
  {
    id: 6,
    dimension: 'SN',
    locales: {
      ko: { text: '정보를 받아들일 때?', optionA: '사실과 세부 정보에 집중한다', optionB: '패턴과 가능성을 먼저 본다' },
      en: { text: 'When taking in information, you…', optionA: 'Focus on facts and concrete details', optionB: 'Notice patterns and possibilities first' },
      ja: { text: '情報を受け取るとき？', optionA: '事実と具体的な詳細に注目する', optionB: 'まずパターンと可能性を見る' },
      zh: { text: '接收信息时，你…', optionA: '关注事实与具体细节', optionB: '先看到模式与可能性' },
      es: { text: 'Al recibir información…', optionA: 'Te centras en hechos y detalles concretos', optionB: 'Primero ves patrones y posibilidades' },
      fr: { text: 'Quand vous recevez des informations…', optionA: 'Vous vous concentrez sur les faits et les détails concrets', optionB: 'Vous repérez d’abord les schémas et les possibilités' },
      de: { text: 'Wenn Sie Informationen aufnehmen…', optionA: 'Konzentrieren Sie sich auf Fakten und konkrete Details', optionB: 'Erkennen Sie zuerst Muster und Möglichkeiten' },
      vi: { text: 'Khi tiếp nhận thông tin, bạn…', optionA: 'Tập trung vào sự thật và chi tiết cụ thể', optionB: 'Nhận ra các mẫu và khả năng trước tiên' },
      th: { text: 'เมื่อรับข้อมูล คุณจะ…', optionA: 'โฟกัสข้อเท็จจริงและรายละเอียดที่เป็นรูปธรรม', optionB: 'มองเห็นแพตเทิร์นและความเป็นไปได้ก่อน' },
      id: { text: 'Saat menerima informasi…', optionA: 'Fokus pada fakta dan detail konkret', optionB: 'Melihat pola dan kemungkinan dulu' },
      pt: { text: 'Ao receber informações…', optionA: 'Você se concentra em fatos e detalhes concretos', optionB: 'Você vê primeiro padrões e possibilidades' },
      hi: { text: 'जानकारी लेते समय, आप…', optionA: 'तथ्यों और ठोस विवरण पर ध्यान देते हैं', optionB: 'पहले पैटर्न और संभावनाएँ देखते हैं' },
    },
  },
  {
    id: 7,
    dimension: 'TF',
    locales: {
      ko: { text: '결정을 내릴 때?', optionA: '논리와 객관적 기준을 중시한다', optionB: '사람들의 감정과 가치를 중시한다' },
      en: { text: 'When making decisions, you…', optionA: 'Prioritize logic and objective criteria', optionB: 'Prioritize people’s feelings and values' },
      ja: { text: '決断するとき？', optionA: '論理と客観的基準を重視する', optionB: '人の感情と価値を重視する' },
      zh: { text: '做决定时，你…', optionA: '重视逻辑与客观标准', optionB: '重视他人的感受与价值观' },
      es: { text: 'Al tomar decisiones…', optionA: 'Priorizas la lógica y criterios objetivos', optionB: 'Priorizas los sentimientos y valores de las personas' },
      fr: { text: 'Quand vous prenez des décisions…', optionA: 'Vous privilégiez la logique et des critères objectifs', optionB: 'Vous privilégiez les sentiments et les valeurs des personnes' },
      de: { text: 'Wenn Sie Entscheidungen treffen…', optionA: 'Priorisieren Sie Logik und objektive Kriterien', optionB: 'Priorisieren Sie die Gefühle und Werte der Menschen' },
      vi: { text: 'Khi đưa ra quyết định, bạn…', optionA: 'Ưu tiên logic và tiêu chí khách quan', optionB: 'Ưu tiên cảm xúc và giá trị của con người' },
      th: { text: 'เมื่อคุณต้องตัดสินใจ คุณจะ…', optionA: 'ให้ความสำคัญกับตรรกะและเกณฑ์ที่เป็นกลาง', optionB: 'ให้ความสำคัญกับความรู้สึกและคุณค่าของผู้คน' },
      id: { text: 'Saat mengambil keputusan…', optionA: 'Memprioritaskan logika dan kriteria objektif', optionB: 'Memprioritaskan perasaan dan nilai orang lain' },
      pt: { text: 'Ao tomar decisões…', optionA: 'Você prioriza a lógica e critérios objetivos', optionB: 'Você prioriza os sentimentos e valores das pessoas' },
      hi: { text: 'निर्णय लेते समय, आप…', optionA: 'तर्क और वस्तुनिष्ठ मानदंडों को प्राथमिकता देते हैं', optionB: 'लोगों की भावनाओं और मूल्यों को प्राथमिकता देते हैं' },
    },
  },
  {
    id: 8,
    dimension: 'JP',
    locales: {
      ko: { text: '업무 스타일은?', optionA: '마감일 전에 미리 완료한다', optionB: '마감일에 임박해서 집중력이 높아진다' },
      en: { text: 'Your work style is…', optionA: 'Finishing well before the deadline', optionB: 'Focusing hardest as the deadline approaches' },
      ja: { text: '仕事のスタイルは？', optionA: '締切前に早めに終える', optionB: '締切が近づくと集中力が上がる' },
      zh: { text: '你的工作风格是…', optionA: '在截止日期前提前完成', optionB: '临近截止时专注力更强' },
      es: { text: 'Tu estilo de trabajo…', optionA: 'Terminar con tiempo antes del plazo', optionB: 'Concentrarte más cuando se acerca la fecha límite' },
      fr: { text: 'Votre style de travail, c’est…', optionA: 'Terminer bien avant la date limite', optionB: 'Vous concentrer davantage quand l’échéance approche' },
      de: { text: 'Ihr Arbeitsstil ist…', optionA: 'Deutlich vor der Frist fertig zu werden', optionB: 'Sich stärker zu konzentrieren, wenn die Frist näher rückt' },
      vi: { text: 'Phong cách làm việc của bạn là…', optionA: 'Hoàn thành công việc sớm hơn nhiều trước hạn', optionB: 'Tập trung cao nhất khi hạn chót đến gần' },
      th: { text: 'สไตล์การทำงานของคุณคือ…', optionA: 'ทำงานเสร็จก่อนกำหนดค่อนข้างมาก', optionB: 'โฟกัสได้ดีที่สุดเมื่อเดดไลน์ใกล้เข้ามา' },
      id: { text: 'Gaya kerjamu…', optionA: 'Menyelesaikan jauh sebelum tenggat', optionB: 'Lebih fokus saat deadline mendekat' },
      pt: { text: 'Seu estilo de trabalho é…', optionA: 'Terminar com bastante antecedência ao prazo', optionB: 'Concentrar mais quando o prazo se aproxima' },
      hi: { text: 'आपका कार्य शैली…', optionA: 'समय सीमा से काफी पहले पूरा करना', optionB: 'समय सीमा नज़दीक आने पर अधिक एकाग्र होना' },
    },
  },
  {
    id: 9,
    dimension: 'EI',
    locales: {
      ko: { text: '모임에서 당신은?', optionA: '먼저 말을 걸고 대화를 시작한다', optionB: '누군가 말을 걸어주길 기다린다' },
      en: { text: 'In a group, you…', optionA: 'Start conversations first', optionB: 'Wait for someone else to speak to you' },
      ja: { text: '集まりではあなたは？', optionA: '先に話しかけて会話を始める', optionB: '誰かが話しかけるのを待つ' },
      zh: { text: '在聚会中，你…', optionA: '主动开口聊天', optionB: '等别人先跟你说话' },
      es: { text: 'En un grupo…', optionA: 'Inicias la conversación primero', optionB: 'Esperas a que alguien te hable' },
      fr: { text: 'Dans un groupe…', optionA: 'Vous lancez la conversation en premier', optionB: 'Vous attendez que quelqu’un vienne vous parler' },
      de: { text: 'In einer Gruppe…', optionA: 'Beginnen Sie Gespräche zuerst', optionB: 'Warten Sie, bis jemand Sie anspricht' },
      vi: { text: 'Trong một nhóm, bạn…', optionA: 'Chủ động bắt chuyện trước', optionB: 'Chờ người khác đến nói chuyện với mình' },
      th: { text: 'ในกลุ่มคน คุณจะ…', optionA: 'เริ่มบทสนทนาก่อน', optionB: 'รอให้คนอื่นเข้ามาคุยก่อน' },
      id: { text: 'Dalam kelompok…', optionA: 'Memulai percakapan lebih dulu', optionB: 'Menunggu orang lain menyapa' },
      pt: { text: 'Em um grupo…', optionA: 'Você inicia a conversa primeiro', optionB: 'Você espera alguém falar com você' },
      hi: { text: 'समूह में, आप…', optionA: 'पहले बातचीत शुरू करते हैं', optionB: 'किसी के संपर्क करने का इंतज़ार करते हैं' },
    },
  },
  {
    id: 10,
    dimension: 'SN',
    locales: {
      ko: { text: '책이나 영화를 볼 때?', optionA: '현실적이고 실용적인 내용을 선호한다', optionB: '상상력을 자극하는 판타지를 좋아한다' },
      en: { text: 'For books or movies, you…', optionA: 'Prefer realistic, practical stories', optionB: 'Enjoy imaginative fantasy that sparks ideas' },
      ja: { text: '本や映画では？', optionA: '現実的で実用的な内容を好む', optionB: '想像力を刺激するファンタジーが好き' },
      zh: { text: '看书或电影时，你…', optionA: '偏好现实、实用的内容', optionB: '喜欢激发想象力的奇幻作品' },
      es: { text: 'Con libros o películas…', optionA: 'Prefieres historias realistas y prácticas', optionB: 'Disfrutas la fantasía que estimula la imaginación' },
      fr: { text: 'Pour les livres ou les films…', optionA: 'Vous préférez des histoires réalistes et concrètes', optionB: 'Vous aimez la fantaisie qui stimule l’imagination' },
      de: { text: 'Bei Büchern oder Filmen…', optionA: 'Bevorzugen Sie realistische, praktische Geschichten', optionB: 'Genießen Sie Fantasie, die die Vorstellungskraft anregt' },
      vi: { text: 'Với sách hoặc phim, bạn…', optionA: 'Thích các câu chuyện thực tế, mang tính ứng dụng', optionB: 'Thích thể loại giả tưởng khơi gợi trí tưởng tượng' },
      th: { text: 'สำหรับหนังสือหรือภาพยนตร์ คุณจะ…', optionA: 'ชอบเรื่องที่สมจริงและใช้ได้จริง', optionB: 'ชอบแฟนตาซีที่กระตุ้นจินตนาการ' },
      id: { text: 'Untuk buku atau film…', optionA: 'Lebih suka cerita realistis dan praktis', optionB: 'Menikmati fantasi yang memicu imajinasi' },
      pt: { text: 'Com livros ou filmes…', optionA: 'Você prefere histórias realistas e práticas', optionB: 'Você gosta de fantasia que estimula a imaginação' },
      hi: { text: 'किताब या फ़िल्म के लिए, आप…', optionA: 'यथार्थवादी, व्यावहारिक कहानियाँ पसंद करते हैं', optionB: 'कल्पना को उत्तेजित करने वाली फ़ैंटेसी का आनंद लेते हैं' },
    },
  },
  {
    id: 11,
    dimension: 'TF',
    locales: {
      ko: { text: '갈등 상황에서?', optionA: '공정하고 원칙에 따라 해결한다', optionB: '조화와 관계 유지를 우선시한다' },
      en: { text: 'In conflict, you…', optionA: 'Resolve things fairly by principle', optionB: 'Prioritize harmony and keeping the relationship' },
      ja: { text: '対立の場面では？', optionA: '公正さと原則で解決する', optionB: '調和と関係維持を優先する' },
      zh: { text: '发生冲突时，你…', optionA: '按原则公正解决', optionB: '优先维护和谐与关系' },
      es: { text: 'En un conflicto…', optionA: 'Resuelves con justicia y principios', optionB: 'Priorizas la armonía y mantener la relación' },
      fr: { text: 'En situation de conflit…', optionA: 'Vous cherchez une solution juste, fondée sur des principes', optionB: 'Vous privilégiez l’harmonie et le maintien de la relation' },
      de: { text: 'In einer Konfliktsituation…', optionA: 'Lösen Sie es fair und nach Prinzipien', optionB: 'Priorisieren Sie Harmonie und den Erhalt der Beziehung' },
      vi: { text: 'Trong tình huống xung đột, bạn…', optionA: 'Giải quyết công bằng theo nguyên tắc', optionB: 'Ưu tiên sự hài hòa và duy trì mối quan hệ' },
      th: { text: 'ในสถานการณ์ขัดแย้ง คุณจะ…', optionA: 'แก้ปัญหาอย่างยุติธรรมตามหลักการ', optionB: 'ให้ความสำคัญกับความกลมกลืนและการรักษาความสัมพันธ์' },
      id: { text: 'Saat konflik…', optionA: 'Menyelesaikan secara adil dengan prinsip', optionB: 'Memprioritaskan harmoni dan hubungan' },
      pt: { text: 'Em um conflito…', optionA: 'Você resolve com justiça e princípios', optionB: 'Você prioriza a harmonia e manter o relacionamento' },
      hi: { text: 'संघर्ष में, आप…', optionA: 'सिद्धांत के अनुसार निष्पक्ष रूप से हल करते हैं', optionB: 'सामंजस्य और संबंध बनाए रखने को प्राथमिकता देते हैं' },
    },
  },
  {
    id: 12,
    dimension: 'JP',
    locales: {
      ko: { text: '일상생활에서?', optionA: '규칙적인 루틴을 선호한다', optionB: '유연하게 상황에 맞춰 변한다' },
      en: { text: 'In daily life, you…', optionA: 'Prefer a regular routine', optionB: 'Adapt flexibly to whatever comes up' },
      ja: { text: '日常生活では？', optionA: '規則的なルーティンを好む', optionB: '状況に合わせて柔軟に変える' },
      zh: { text: '在日常生活中，你…', optionA: '喜欢规律的作息', optionB: '灵活适应变化' },
      es: { text: 'En la vida diaria…', optionA: 'Prefieres una rutina regular', optionB: 'Te adaptas con flexibilidad a lo que surja' },
      fr: { text: 'Dans la vie quotidienne…', optionA: 'Vous préférez une routine régulière', optionB: 'Vous vous adaptez avec souplesse à ce qui se présente' },
      de: { text: 'Im Alltag…', optionA: 'Bevorzugen Sie eine regelmäßige Routine', optionB: 'Passen Sie sich flexibel an, was auch immer auftaucht' },
      vi: { text: 'Trong cuộc sống hằng ngày, bạn…', optionA: 'Thích một lịch sinh hoạt đều đặn', optionB: 'Linh hoạt thích nghi với tình huống phát sinh' },
      th: { text: 'ในชีวิตประจำวัน คุณจะ…', optionA: 'ชอบกิจวัตรที่สม่ำเสมอ', optionB: 'ปรับตัวได้ยืดหยุ่นตามสถานการณ์ที่เกิดขึ้น' },
      id: { text: 'Dalam kehidupan sehari-hari…', optionA: 'Lebih suka rutinitas teratur', optionB: 'Beradaptasi fleksibel sesuai situasi' },
      pt: { text: 'Na vida diária…', optionA: 'Você prefere uma rotina regular', optionB: 'Você se adapta com flexibilidade ao que surgir' },
      hi: { text: 'दैनिक जीवन में, आप…', optionA: 'नियमित दिनचर्या पसंद करते हैं', optionB: 'आने वाली परिस्थितियों के अनुसार लचीले ढंग से अनुकूल होते हैं' },
    },
  },
]
